### ISSUE TITLE
Leaflet 1.0-dev support

### ISSUE THREAD

**Issue by pawelantczak** [ismyrnow/leaflet-groupedlayercontrol#23]
Hello.

Due to massive api update in Leaflet 1.0, plugin is not working.
Error: `Uncaught TypeError: this.callInitHooks is not a function`

Do you plan to add support for 1.0?

**Comment by ismyrnow** [comment]
I don't currently use the plugin in any of my apps, so probably not.
However, I am happy to accept a pull request with this functionality, or a
gittip (or similar) to fund the effort.

**Comment by dosstx** [comment]
This is the best plugin out there. I use it for my apps but not smart enough to code the update. Just putting my vote here. If I can help let me know.

**Comment by ismyrnow** [comment]
If anyone is interested in updating this plugin to work with Leaflet v1.0, feel free to open a PR for it. I'll leave the issue open for now.

**Comment by arch1v1st** [comment]
+1!

**Comment by McCABRUS** [comment]
is someone working on this update?

**Comment by ismyrnow** [comment]
I have an open PR that is ready to be merged, but I'm in the process of
moving to another state (packing the truck tomorrow!) and haven't had a
chance to sit down and do it.

**Comment by ismyrnow** [comment]
It looks like I was mistaken. The PR is for another Leaflet plugin of mine. This one is still up for grabs.

You can also check the existing forks (there are 44 of them right now). It's possible one of them includes a v1 update, and they just haven't opened a PR for it.

**Comment by Siliconrob** [comment]
I would think this probably works as a fork of a fork with enhancements for icons is something I am using now for grouped layer controls https://github.com/SGSIMapping/leaflet-sgsilayercontrol and it is working with Leaflet 1.0.1

I could fix this up if you have a specific set of layers you want to test on

**Comment by ismyrnow** [comment]
I'm not sure if that's a fork or a totally different plugin which just has a similar use case. The API is different, so it's probably not a good candidate for a v1 of this plugin.

**Comment by Siliconrob** [comment]
Going to give it a shot.

**Comment by chugcup** [comment]
I had this requirement in my app so I went ahead and fixed up the code to use the new internal `_layers` format.

https://github.com/ismyrnow/Leaflet.groupedlayercontrol/pull/42

I had another app that still used 0.7.3 so I verified it would maintain backwards-compatibility.

**Comment by deeg** [comment]
@ismyrnow, can this be closed now that it works with 1.0?

**Comment by faipassa** [comment]
@deeg Look at v0.6.0. It is fully functional with leaflet 1.0

**Comment by deeg** [comment]
@faipassa, yes I noticed that, which is why I'm saying this issue could be closed so people don't think it doesn't work with 1.0
